"""Player interface. OBS is one backend. Tests use FakePlayer."""

from typing import Protocol


class Player(Protocol):
    def get_program_state(self) -> dict: ...

    def set_layout(self, name: str) -> None: ...

    def play_clip(self, path: str) -> None: ...

    def set_speaking(self, host: str | None) -> None: ...

    def set_center(self, kind: str, data: dict | None) -> None: ...

    def set_headline(self, text: str) -> None: ...

    def set_name_bar(self, host: str, name: str, handle: str) -> None: ...

    def duck_music(self, db: float) -> None: ...
